version: '3'
services:
  api:
    container_name: 'go-api'
    build: ./api
    restart: always
    ports:
      - 80:80       # Restful
      - 50051:50051 # gRPC
    links:
      - redis

  redis:
    container_name: 'redis-db'
    image: 'redis:9-bullseye'