version: '3'
services:
  api:
    container_name: 'go-api'
    build: ./api
    restart: always
    ports:
      - 80:80
    links:
      - redis

  redis:
    container_name: 'redis-db'
    image: 'redis:6-bullseye'